--
-- Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
-- For more information please visit http://www.spoledge.com
--

-- ======================== Oracle P R O L O G ====================
-- manually: DROP USER __USERNAME__;
-- manually: CREATE user __USERNAME__ IDENTIFIED BY your_password;
-- manually: GRANT CONNECT, RESOURCE, CREATE VIEW TO __USERNAME__;

		


-- ======================== TABLE securityQnA ====================
CREATE TABLE securityQnA (
	id number(19) NOT NULL,
	username varchar2(30) NOT NULL,
	password varchar2(30) NOT NULL,
	question varchar2(500) NOT NULL,
	answer varchar2(500) NOT NULL
);

ALTER TABLE securityQnA ADD CONSTRAINT pk_securityQnA PRIMARY KEY (
	id
);

CREATE UNIQUE INDEX inx_qna ON securityQnA (
	question
);

CREATE SEQUENCE seq_securityQnA;


-- ==================== F O R E I G N   K E Y S  ====================
-- ======================== D A T A ========================
-- ======================== Oracle E P I L O G ====================

