CREATE OR REPLACE TRIGGER SBREXT." _TRG" 
 BEFORE INSERT OR UPDATE
 ON USER_SECURITY_QUESTIONS
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
-- PL/SQL Block
BEGIN

  IF :new.DATE_MODIFIED IS NULL THEN
    :new.DATE_MODIFIED := SYSDATE;
  END IF;

END;