--
-- Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
-- For more information please visit http://www.spoledge.com
--

-- ======================== P R O L O G ====================
-- ==================== F O R E I G N   K E Y S  ====================
drop table securityQnA CASCADE CONSTRAINTS;

-- ======================== Oracle E P I L O G ====================

DROP SEQUENCE seq_securityQnA;
